server:
  port: 8762

spring:
  application:
    name: springcloud-config

#security:
#  basic:
#    enabled: true #开启认证
#  user:
#    name: user
#    password: 123456

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: false #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中