server:
  port: 8765 #服务端口

spring: 
  application:  
    name: springcloud-microA #指定服务名
  datasource:
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;useSSL=false
    username: ${username}
    password: ${password}

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:

pagehelper:
  helperDialect: mysql
  resonable: true
  supportMethodsArguments: true
  params: count=conutSql

management:
  security:
    enabled: false #是否开启actuator安全认证